### ISSUE TITLE
Out Of Bounds Exception 

### ISSUE THREAD

**Issue by r0754329** [Actelion/openchemlib#105]
When running datasets in smiles format I often get stuck on following error message: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 6
 at com.actelion.research.chem.Molecule.setBondType(Molecule.java:3458)
 at com.actelion.research.chem.ExtendedMolecule.rescueStereoBonds(ExtendedMolecule.java:328)
 at com.actelion.research.chem.ExtendedMolecule.copyMoleculeByBonds(ExtendedMolecule.java:275)
 at com.actelion.research.chem.mcs.BondVector2IdCode.convert(BondVector2IdCode.java:184)
 at com.actelion.research.chem.mcs.BondVector2IdCode.getFragmentIdCode(BondVector2IdCode.java:102)
 at com.actelion.research.chem.mcs.RunBondVector2IdCode.run(RunBondVector2IdCode.java:92)
 at java.base/java.lang.Thread.run(Thread.java:829)

Is there a way to solve this because I don't see any problems in my dataset

**Comment by thsa** [comment]
can you send me a smiles where this happens and the steps needed to reproduce the problem?

Thanks in advance...

**Comment by r0754329** [comment]
Dear

Thank you for the prompt respons! Following SMILES string gives me the issues: O=C(C[C@***@***.******@***.***(C[C@](O)(C3)C1)C2)NCc1ccc(N2CCCC2=O)cc1. This is the command that I use to run the openchemlib:  java -server -Xmx50g -classpath ${Openchemlib_dir}/openchemlib-2024.2.3-SNAPSHOT.jar com.actelion.research.chem.properties.fractaldimension.FractalDimensionMoleculeMain -i <input_file> -w <output path>

Thank you in advance!

Best wishes,
Mathieu Cnudde

________________________________

**Comment by r0754329** [comment]
O=C(C[C@]12C[C@H]3C[C@H](C[C@](O)(C3)C1)C2)NCc1ccc(N2CCCC2=O)cc1 --> correct one

**Comment by thsa** [comment]
not a valid smiles: the ring with 3 doesn't close; second ring with 1 doesn't close either; C@H probably belongs into square brackets. This looks a little like an 'AI'-generated pseudo-SMILES

**Comment by sergio-gomez** [comment]
I get the same error with the second molecule in the fiveMolecules.smi file in the examples/FractalDimension folder:
O=C(C[C@@H]1OCC=C2[C@H](C3)[C@@H]1[C@H]1[C@@]4(CC5)[C@H]3N5C2)N1c1c4cccc1

Output:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 5
        at com.actelion.research.chem.Molecule.setBondType(Molecule.java:3496)
        at com.actelion.research.chem.ExtendedMolecule.rescueStereoBonds(ExtendedMolecule.java:325)
        at com.actelion.research.chem.ExtendedMolecule.copyMoleculeByBonds(ExtendedMolecule.java:272)
        at com.actelion.research.chem.mcs.BondVector2IdCode.convert(BondVector2IdCode.java:184)
        at com.actelion.research.chem.mcs.BondVector2IdCode.getFragmentIdCode(BondVector2IdCode.java:102)
        at com.actelion.research.chem.mcs.RunBondVector2IdCode.run(RunBondVector2IdCode.java:92)
        at java.base/java.lang.Thread.run(Thread.java:1570)

I've tried with 1GB, 3GB, and 6GB for the -Xmx Java parameter, and with Java 8 (Oracle), Java 12 (OpenJDK), and Java 22 (OpenJDK). I downloaded the compiled JAR file from:
https://repo1.maven.org/maven2/com/actelion/research/openchemlib/2024.3.2/openchemlib-2024.3.2.jar
My system is a Windows 11.

Thanks,

Sergio.

**Comment by thsa** [comment]
Hi Sergio, many thanks for being persistent. Github somehow seems to change SMILES strings. We tried with the second from the examples/FractalDimension collection and could reproduce the issue. Since yesterday it should be solved.
Best wishes, Thomas
